BEGIN;

CREATE TABLE IF NOT EXISTS chats (
	id SERIAL PRIMARY KEY,
	user_one_id INTEGER NOT NULL,
	user_two_id INTEGER NOT NULL,
	messages JSONB DEFAULT '[]',
	FOREIGN KEY (user_one_id) REFERENCES users(id) ON DELETE SET NULL,
	FOREIGN KEY (user_two_id) REFERENCES users(id) ON DELETE SET NULL
);

COMMIT;
